[phases.setup]
# Установка зависимостей через pip
run = "pip install -r requirements.txt"

[phases.build]
# Миграции базы данных и сборка статических файлов
run = """
python manage.py migrate
python manage.py collectstatic --noinput
"""

[phases.start]
# Запуск сервера
run = "python manage.py runserver 0.0.0.0:8000"